import { useState } from "react";
import { DashboardLayout, IconButtonView, ToastProvider, type SidebarNavItem } from "@basekit/ui";
import { Buttons, DataDisplay, DateCalendar, Feedback, Forms, Foundations, Inputs, Layout, Overlays, Selection, Sliders } from "./pages/ShowcasePages";
type PageId = "foundations"|"buttons"|"inputs"|"selection"|"date"|"feedback"|"overlays"|"layout"|"data"|"forms"|"sliders";
const pages: Record<PageId, React.ReactNode> = { foundations:<Foundations/>, buttons:<Buttons/>, inputs:<Inputs/>, selection:<Selection/>, date:<DateCalendar/>, feedback:<Feedback/>, overlays:<Overlays/>, layout:<Layout/>, data:<DataDisplay/>, forms:<Forms/>, sliders:<Sliders/> };
const nav: { id: PageId; label: string; icon: SidebarNavItem["icon"] }[] = [
 {id:"foundations",label:"Foundations",icon:"info"},{id:"buttons",label:"Buttons",icon:"check"},{id:"inputs",label:"Inputs",icon:"settings"},{id:"selection",label:"Selection",icon:"filter"},{id:"date",label:"Date & Calendar",icon:"calendar" as any},{id:"feedback",label:"Feedback",icon:"info"},{id:"overlays",label:"Overlays",icon:"external"},{id:"layout",label:"Layout",icon:"menu"},{id:"data",label:"Data Display",icon:"list" as any},{id:"forms",label:"Forms",icon:"check"},{id:"sliders",label:"Sliders",icon:"settings"}
];
export const App=()=>{ const [page,setPage]=useState<PageId>("foundations"); const [dark,setDark]=useState(false); return <ToastProvider><DashboardLayout brand={<span className="text-lg font-bold">Base<span className="text-primary">Kit</span></span>} navItems={nav.map(i=>({...i,active:page===i.id,onClick:()=>setPage(i.id)}))} topbarTitle={nav.find(n=>n.id===page)?.label} topbarActions={<IconButtonView icon="settings" aria-label="Basculer le thème" variant="outline" onClick={()=>{const n=!dark; setDark(n); document.documentElement.classList.toggle("dark",n);}}/>} footer="BaseKit — bibliothèque UI générique, design system et renderer déclaratif.">{pages[page]}</DashboardLayout></ToastProvider> };
